remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-remote-theme

title: "Billy's blog"
description: "Billy's blog about coding and stuff"
baseurl: "/"
url: "https://tomlin7.github.io"

home_page: "index.md"

header_pages:
  - about.md
  - contact.md

header_links:
  - title: "biscuit"
    url: "https://tomlin7.github.io/biscuit"

style: dark

footer: 'copyright &copy; <a href="https://github.com/tomlin7">tomlin7</a>'

# Build settings
markdown: kramdown
remote_theme: tomlin7/jekyll-theme-console
